In [1]:
from misc import *

In [2]:
spectrum = np.arange(1,101.,1.).reshape(10,-1)

In [7]:
spectrum

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.],
       [ 31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.],
       [ 41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.],
       [ 51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.],
       [ 61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.],
       [ 71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.],
       [ 81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.],
       [ 91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100.]])

In [6]:
get_ham_misc(spectrum, individual=True, spectral_width=(0.,1.))

[array([ 5.5, 15.5, 25.5, 35.5, 45.5, 55.5, 65.5, 75.5, 85.5, 95.5]),
 array([  30.25,  240.25,  650.25, 1260.25, 2070.25, 3080.25, 4290.25,
        5700.25, 7310.25, 9120.25]),
 array([  38.5,  248.5,  658.5, 1268.5, 2078.5, 3088.5, 4298.5, 5708.5,
        7318.5, 9128.5]),
 array([8.25, 8.25, 8.25, 8.25, 8.25, 8.25, 8.25, 8.25, 8.25, 8.25])]

In [6]:
spectrum_=np.mean(spectrum, axis=1)

In [10]:
np.mean(spectrum)

50.5

In [15]:
np.mean(spectrum_[:,None], axis=0, keepdims=True)

array([[50.5]])

In [10]:
np.mean([i for i in range(1, 11)])**2

30.25